=== dgcastillof/morfemalibreria/books.schema.json
{
  "$schema": "http://json-schema.org/draft-07/schema#",
  "type": "array",
  "items": {
    "type": "object",
    "required": [
      "id",
      "titulo",
      "idioma",
      "autor",
      "estado",
      "precio",
      "imagen",
      "vendido"
    ],
    "properties": {
      "id": { "type": "integer" },
      "titulo": { "type": "string" },
      "idioma": { "type": "string" },
      "autor": { "type": "string" },
      "estado": { "type": "string" },
      "precio": { "type": "string" },
      "imagen": { "type": "string" },
      "vendido": { "type": "boolean" },
      "novedad": { "type": "boolean" }
    },
    "additionalProperties": false
  }
}

=== dgcastillof/morfemalibreria/public/books.json
[
    {
        "id": 1,
        "titulo": "Gallant",
        "idioma": "Español",
        "autor": "V. E. Schwab",
        "estado": "Como nuevo",
        "precio": "$11500",
        "imagen": "fotos/gallant.png",
        "vendido": false
    },
    {
        "id": 2,
        "titulo": "Lore",
        "idioma": "Español",
        "autor": "Alexandra Bracken",
        "estado": "Muy bueno",
        "precio": "$11500",
        "imagen": "fotos/lore.png",
        "vendido": false
    },
    {
        "id": 3,
        "titulo": "Cinder",
        "idioma": "Español",
        "autor": "Marissa Meyer",
        "estado": "Como nuevo",
        "precio": "$9500",
        "imagen": "fotos/cinder.png",
        "vendido": false
    },
    {
        "id": 4,
        "titulo": "Ella que llegó a ser el sol",
        "idioma": "Español",
        "autor": "Shelley Parker-Chan",
        "estado": "Como nuevo",
        "precio": "$15500",
        "imagen": "fotos/ella_que_llego_a_ser_el_sol.png",
        "vendido": false
    },
    {
        "id": 5,
        "titulo": "Nuestra parte de noche",
        "idioma": "Español",
        "autor": "Mariana Enriquez",
        "estado": "Como nuevo",
        "precio": "$18500",
        "imagen": "fotos/nuestra_parte_de_noche.png",
        "vendido": true
    },
    {
        "id": 6,
        "titulo": "La teoría de Joa",
        "idioma": "Español",
        "autor": "Agus Grimm Pitch",
        "estado": "Como nuevo",
        "precio": "$8000",
        "imagen": "fotos/la_teoria_de_joa.png",
        "vendido": false
    },
    {
        "id": 7,
        "titulo": "Tierra del Fuego: la creación del fin del mundo",
        "idioma": "Español",
        "autor": "Guillermo Gucci",
        "estado": "Como nuevo",
        "precio": "$8000",
        "imagen": "fotos/tierra_del_fuego_la_creacion_del_fin_del_mundo.png",
        "vendido": false
    },
    {
        "id": 8,
        "titulo": "Eclosión",
        "idioma": "Español",
        "autor": "Vera Spinetta",
        "estado": "Como nuevo",
        "precio": "$4000",
        "imagen": "fotos/eclosion.png",
        "vendido": false
    },
    {
        "id": 9,
        "titulo": "Cadáver exquisito",
        "idioma": "Español",
        "autor": "Agustina Bazterrica",
        "estado": "Como nuevo",
        "precio": "$23000",
        "imagen": "fotos/cadaver_exquisito.png",
        "vendido": true
    },
    {
        "id": 10,
        "titulo": "Las indignas",
        "idioma": "Español",
        "autor": "Agustina Bazterrica",
        "estado": "Como nuevo",
        "precio": "$14000",
        "imagen": "fotos/las_indignas.png",
        "vendido": false
    },
    {
        "id": 11,
        "titulo": "Mitos, dogmas y epopeyas",
        "idioma": "Español",
        "autor": "Agustín A. Monteverde",
        "estado": "Como nuevo",
        "precio": "$19000",
        "imagen": "fotos/mitos_dogmas_y_epopeyas.png",
        "vendido": false
    },
    {
        "id": 12,
        "titulo": "This Is How You Lose the Time War",
        "idioma": "Inglés",
        "autor": "Amal El-Mohtar, Max Gladstone",
        "estado": "Detalles",
        "precio": "$4500",
        "imagen": "fotos/this_is_how_you_lose_the_time_war.png",
        "vendido": true
    },
    {
        "id": 13,
        "titulo": "Un mundo feliz",
        "idioma": "Español",
        "autor": "Aldous Huxley",
        "estado": "Como nuevo",
        "precio": "$8000",
        "imagen": "fotos/un_mundo_feliz.png",
        "vendido": false
    },
    {
        "id": 14,
        "titulo": "Aniquilación",
        "idioma": "Español",
        "autor": "Jeff Vandermeer",
        "estado": "Como nuevo",
        "precio": "$14000",
        "imagen": "fotos/aniquilacion.png",
        "vendido": false
    },
    {
        "id": 15,
        "titulo": "El señor de los anillos II - Las dos torres",
        "idioma": "Español",
        "autor": "J. R. R. Tolkien",
        "estado": "Como nuevo",
        "precio": "$15500",
        "imagen": "fotos/el_señor_de_los_anillos_ii_las_dos_torres.png",
        "vendido": false
    },
    {
        "id": 16,
        "titulo": "El señor de los anillos I - La comunidad del anillo",
        "idioma": "Español",
        "autor": "J. R. R. Tolkien",
        "estado": "Como nuevo",
        "precio": "$11500",
        "imagen": "fotos/el_señor_de_los_anillos_i_la_comunidad_del_anillo.png",
        "vendido": true
    },
    {
        "id": 17,
        "titulo": "Entremuros",
        "idioma": "Español",
        "autor": "Robert Jackson Bennett",
        "estado": "Como nuevo",
        "precio": "$11500",
        "imagen": "fotos/entremuros.png",
        "vendido": false
    },
    {
        "id": 18,
        "titulo": "Viuda de hierro",
        "idioma": "Español",
        "autor": "Xiran Jay Zhao",
        "estado": "Como nuevo",
        "precio": "$19000",
        "imagen": "fotos/viuda_de_hierro.png",
        "vendido": false
    },
    {
        "id": 19,
        "titulo": "Casa de tierra y sangre",
        "idioma": "Español",
        "autor": "Sarah J. Maas",
        "estado": "Como nuevo",
        "precio": "$23000",
        "imagen": "fotos/casa_de_tierra_y_sangre.png",
        "vendido": false
    },
    {
        "id": 20,
        "titulo": "Éste es el mar",
        "idioma": "Español",
        "autor": "Mariana Enriquez",
        "estado": "Muy bueno",
        "precio": "$6500",
        "imagen": "fotos/este_es_el_mar.png",
        "vendido": true
    },
    {
        "id": 21,
        "titulo": "Esquirla del amanecer",
        "idioma": "Español",
        "autor": "Brandon Sanderson",
        "estado": "Como nuevo",
        "precio": "$25000",
        "imagen": "fotos/esquirla_del_amanecer.png",
        "vendido": false
    },
    {
        "id": 22,
        "titulo": "Sombras de identidad",
        "idioma": "Español",
        "autor": "Brandon Sanderson",
        "estado": "Como nuevo",
        "precio": "$27500",
        "imagen": "fotos/sombras_de_identidad.png",
        "vendido": true
    },
    {
        "id": 23,
        "titulo": "Aleación de ley",
        "idioma": "Español",
        "autor": "Brandon Sanderson",
        "estado": "Muy bueno",
        "precio": "$19000",
        "imagen": "fotos/aleacion_de_ley.png",
        "vendido": false
    },
    {
        "id": 24,
        "titulo": "El metal perdido",
        "idioma": "Español",
        "autor": "Brandon Sanderson",
        "estado": "Como nuevo",
        "precio": "$31500",
        "imagen": "fotos/el_metal_perdido.png",
        "vendido": true
    },
    {
        "id": 25,
        "titulo": "Brazales de duelo",
        "idioma": "Español",
        "autor": "Brandon Sanderson",
        "estado": "Como nuevo",
        "precio": "$26500",
        "imagen": "fotos/brazales_de_duelo.png",
        "vendido": true
    },
    {
        "id": 26,
        "titulo": "Firefight",
        "idioma": "Español",
        "autor": "Brandon Sanderson",
        "estado": "Como nuevo",
        "precio": "$27500",
        "imagen": "fotos/firefight.png",
        "vendido": false
    },
    {
        "id": 27,
        "titulo": "Steelheart",
        "idioma": "Español",
        "autor": "Brandon Sanderson",
        "estado": "Muy bueno",
        "precio": "$23500",
        "imagen": "fotos/steelheart.png",
        "vendido": false
    },
    {
        "id": 28,
        "titulo": "Yumi y el pintor de pesadillas",
        "idioma": "Español",
        "autor": "Brandon Sanderson",
        "estado": "Como nuevo",
        "precio": "$29000",
        "imagen": "fotos/yumi_y_el_pintor_de_pesadillas.png",
        "vendido": false
    },
    {
        "id": 29,
        "titulo": "La novena casa",
        "idioma": "Español",
        "autor": "Leigh Bardugo",
        "estado": "Como nuevo",
        "precio": "$24500",
        "imagen": "fotos/la_novena_casa.png",
        "vendido": false
    },
    {
        "id": 30,
        "titulo": "Trenza del mar esmeralda",
        "idioma": "Español",
        "autor": "Brandon Sanderson",
        "estado": "Como nuevo",
        "precio": "$26500",
        "imagen": "fotos/trenza_del_mar_esmeralda.png",
        "vendido": false
    },
    {
        "id": 31,
        "titulo": "El hombre iluminado",
        "idioma": "Español",
        "autor": "Brandon Sanderson",
        "estado": "Como nuevo",
        "precio": "$26000",
        "imagen": "fotos/el_hombre_iluminado.png",
        "vendido": false
    },
    {
        "id": 32,
        "titulo": "La guía del mago frugal",
        "idioma": "Español",
        "autor": "Brandon Sanderson",
        "estado": "Como nuevo",
        "precio": "$26500",
        "imagen": "fotos/la_guia_del_mago_frugal.png",
        "vendido": false
    },
    {
        "id": 33,
        "titulo": "Cuestiones candentes",
        "idioma": "Español",
        "autor": "Margaret Atwood",
        "estado": "Como nuevo",
        "precio": "$26000",
        "imagen": "fotos/cuestiones_candentes.png",
        "vendido": false
    },
    {
        "id": 34,
        "titulo": "Dónde estás, mundo bello",
        "idioma": "Español",
        "autor": "Sally Rooney",
        "estado": "Como nuevo",
        "precio": "$23000",
        "imagen": "fotos/donde_estas_mundo_bello.png",
        "vendido": true
    },
    {
        "id": 35,
        "titulo": "Los guardianes de almas",
        "idioma": "Español",
        "autor": "Raquel Brune",
        "estado": "Como nuevo",
        "precio": "$23000",
        "imagen": "fotos/los_guardianes_de_almas.png",
        "vendido": false
    },
    {
        "id": 36,
        "titulo": "Me alegro de que mi madre haya muerto",
        "idioma": "Español",
        "autor": "Jennette McCurdy",
        "estado": "Como nuevo",
        "precio": "$16000",
        "imagen": "fotos/me_alegro_de_que_mi_madre_haya_muerto.png",
        "vendido": false
    },
    {
        "id": 37,
        "titulo": "El último hombre blanco",
